# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh 

#Import Files Needed
DOTFILES_PATH=~/dotfiles
ZSH_SRC_PATH=$DOTFILES_PATH/zsh

. "$ZSH_SRC_PATH"/.aliases



# Theme
#ZSH_THEME="gianu"
#ZSH_THEME="pure"
ZSH_THEME="powerlevel10k/powerlevel10k"

source $ZSH/oh-my-zsh.sh 

export DRI_PRIME=1

#for setting history length and file size
HISTSIZE=1000
HISTFILESIZE=2000#plugins


# plugins
plugins=(
  git
  kubectl
  docker
)

# Go
export GOPATH=$HOME/golib
export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
export GOPATH=$GOPATH:/home/aggenikos/code 

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/aggenikos/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/aggenikos/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/home/aggenikos/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/aggenikos/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<


alias dot="cd ~/dotfiles/"
alias rl="source ~/.zshrc; echo '~/.zshrc reloaded.'"
