# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh 

# Theme
ZSH_THEME="gianu"


source $ZSH/oh-my-zsh.sh 

#### Aliases
# nvim

alias vim=nvim
alias vi=nvim

#kubernetes
alias k=kubectl
source <(kubectl completion zsh)
# Public Ip
alias get_ip="curl ipinfo.io/ip"
#alias rm-docker
#alias drma="docker rm `$(docker ps -a -q)`"

#for setting history length and file size
HISTSIZE=1000
HISTFILESIZE=2000#plugins


# plugins
plugins=(
  git
  kubectl
  docker
)

# Go
export GOPATH=$HOME/golib
export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
export GOPATH=$GOPATH:/home/aggenikos/code 

# <<<conda initialize <<<
__conda_setup="$('/home/aggenikos/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/aggenikos/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/home/aggenikos/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/aggenikos/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
